// Gabarits d'export conventionnel par chaîne (P41b) — reproduction fidèle des
// formats papier réels (cf. design-reference/).
//
// DÉCISION : la « journée d'antenne » variable (Al Aoula 07:00, Tamazight 12:00,
// Al Maghribia 07:00) est gérée UNIQUEMENT ici, à l'export. L'app reste en 06:00
// en interne — on ne touche ni semaine.js, ni grilleAxe.js, ni le moteur.
// `debutJourneeMinutes` ne pilote que le TRI des lignes d'un jour et le libellé
// de période de l'export (pas de colonne DB).
//
// `formatHeure` : 'HMS' → "HH:MM:SS" (Al Aoula / Al Maghribia) ; 'HM_POINT' →
// "HH.MM" (Tamazight).

export const GABARIT_DEFAUT = {
  format: 'docx',
  debutJourneeMinutes: 7 * 60, // 07:00
  bilingue: false,
  formatHeure: 'HMS',
  colonnes: ['heure', 'titre', 'duree', 'obs'], // ordre logique RTL : التوقيت | البرامج | المدة | الملاحظات
  logo: null,
  pied: null,
}

const GABARITS = {
  // Al Aoula → .docx : 4 colonnes RTL, un tableau par jour, journée 07:00.
  AW: { ...GABARIT_DEFAUT },

  // Al Maghribia → .pdf « format STM » : même maquette 4 colonnes + logo SNRT
  // + pied de page, journée 07:00.
  AM: { ...GABARIT_DEFAUT, format: 'pdf', logo: '/brand/am.png', pied: 'Generated by STM - SNRT' },

  // Tamazight → .xlsx bilingue : 5 colonnes, heures "HH.MM", journée 12:00.
  TM: {
    format: 'xlsx',
    debutJourneeMinutes: 12 * 60, // 12:00
    bilingue: true,
    formatHeure: 'HM_POINT',
    colonnes: ['titreFr', 'titreAr', 'date', 'heure', 'heureFin'],
    logo: null,
    pied: null,
  },
}

// Arryadia / Athaqafia / Assadissa : pas de format réel fourni → repli sur le
// gabarit .docx Al Aoula (arbitrage utilisateur).
export function gabaritGrilleChaine(codeChaine) {
  return GABARITS[codeChaine] ?? GABARIT_DEFAUT
}

export function libelleFormatHeure(debutJourneeMinutes) {
  const h = String(Math.floor(debutJourneeMinutes / 60)).padStart(2, '0')
  const m = String(debutJourneeMinutes % 60).padStart(2, '0')
  return `${h}:${m}`
}
